# Generated by Django 3.2.4 on 2021-07-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Account.user',),
        ),
    ]
