# Generated by Django 3.2.4 on 2021-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpassword',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
