# Generated by Django 3.2.4 on 2021-07-09 17:38

import Account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_link', models.CharField(blank=True, max_length=30, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(default=Account.utils.get_expiration_time)),
                ('changed', models.BooleanField(default=False)),
                ('request_sent', models.PositiveSmallIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
