# Generated by Django 3.2.4 on 2021-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
