# Generated by Django 3.2.4 on 2021-07-18 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='paid_commission',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='commission',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commission',
            name='recruit',
            field=models.ForeignKey(limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_recruit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='recruit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 1}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.PositiveBigIntegerField(blank=True)),
                ('amount', models.FloatField(default=0.0)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.commission')),
            ],
        ),
    ]
