# Generated by Django 3.2.4 on 2021-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissionpayment',
            options={'verbose_name': 'Commission Transaction', 'verbose_name_plural': 'Commission Transactions'},
        ),
        migrations.AlterField(
            model_name='commissionpayment',
            name='commission',
            field=models.ManyToManyField(blank=True, limit_choices_to={'completed': False}, to='Core.Commission'),
        ),
    ]
