# Generated by Django 3.2.4 on 2021-07-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210719_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionpayment',
            name='commission',
            field=models.ForeignKey(limit_choices_to={'completed': False}, on_delete=django.db.models.deletion.CASCADE, to='Core.commission'),
        ),
    ]
