# Generated by Django 3.2.4 on 2021-07-09 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0002_auto_20210709_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='recruit',
            field=models.OneToOneField(limit_choices_to={'role': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='recruiter',
            field=models.ForeignKey(limit_choices_to={'role': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiter_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
